const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const express=require('express');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const crypto=require('crypto');
const {PGlite}=require('@electric-sql/pglite');
const vault=require('./license-vault');

test('integração PostgreSQL: cadastro, carrinho, pagamento, licenças, perfil e tickets', {timeout:60000}, async t=>{
  process.env.LICENSE_SECRET='integration-license-secret';process.env.JWT_SECRET='integration-jwt-secret';
  process.env.PUBLIC_URL='https://api.example';process.env.CORS_ORIGIN='https://loja.example';
  process.env.TURNSTILE_ENABLED='false';process.env.ADMIN_USER_ID='1';
  const db=new PGlite();t.after(()=>db.close());
  const schema=fs.readFileSync(path.join(__dirname,'schema.sql'),'utf8'),migration=fs.readFileSync(path.join(__dirname,'commerce.sql'),'utf8');
  await db.exec(schema);await db.exec(migration);await db.exec(migration);
  await db.exec('ALTER TABLE licenses ADD COLUMN IF NOT EXISTS key_encrypted TEXT; ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_id TEXT UNIQUE;');
  const pool={async query(sql,args){const r=await db.query(sql,args);return{...r,rowCount:r.affectedRows ?? r.rows.length};},async connect(){return{query:pool.query,release(){}};}};
  const app=express();app.use(express.json());
  const auth=(req,res,next)=>{try{req.user=jwt.verify((req.headers.authorization || '').replace('Bearer ',''),process.env.JWT_SECRET);next();}catch(_){res.status(401).json({error:'Não autenticado.'});}};
  const issueToken=user=>jwt.sign({sub:String(user.id),role:user.role},process.env.JWT_SECRET);
  const fingerprint=key=>crypto.createHash('sha256').update(key).digest('hex');
  const createLicenseKey=slug=>slug+'-'+crypto.randomBytes(12).toString('hex');
  const provisionLicense=async(client,order)=>{const key=createLicenseKey(order.product_slug);await client.query('INSERT INTO licenses(order_id,user_id,product_id,license_key_fingerprint,license_key_hash,key_encrypted) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(order_id) DO NOTHING',[order.order_id,order.user_id,order.product_id,fingerprint(key),await bcrypt.hash(key,4),vault.encrypt(key,order.order_id)]);};
  const payments={};let preferenceCount=0;
  const mercadoPago=async(p,options)=>{
    if(p==='/checkout/preferences'){preferenceCount++;return{id:'preference-'+preferenceCount,init_point:'https://www.mercadopago.com.br/checkout/v1/redirect?pref_id='+preferenceCount};}
    if(p.startsWith('/v1/payments/'))return payments[p.split('/').at(-1)];
    throw Error('Unexpected external operation');
  };
  const {confirmCartPayment}=require('./commerce-api')({app,pool,auth,mercadoPago,provisionLicense});
  require('./customer-api')({app,pool,auth,bcrypt,vault,fingerprint,createLicenseKey,mercadoPago,provisionLicense,confirmCartPayment});
  require('./auth-api')({app,pool,auth,bcrypt,issueToken});
  require('./admin-support-api')({app,pool,auth,bcrypt,vault,fingerprint,createLicenseKey,mercadoPago});
  const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});
  t.after(()=>new Promise(resolve=>server.close(resolve)));
  const base='http://127.0.0.1:'+server.address().port;
  const call=async(method,url,body,token)=>{const r=await fetch(base+url,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)});return{status:r.status,data:await r.json().catch(()=>null)};};
  const register=async(name)=>call('POST','/api/auth/register',{name,email:name+'@example.com',password:'test-password',minecraft_nick:name});
  const a=await register('AdminTest'),b=await register('PlayerTest');assert.equal(a.status,201);assert.equal(b.status,201);
  await db.query("UPDATE users SET role='admin' WHERE id=1");const admin=a.data.token,customer=b.data.token;
  assert.equal((await call('GET','/api/me',undefined,admin)).data.is_admin,true);
  assert.equal((await call('GET','/api/admin/licenses',undefined,customer)).status,403);
  assert.equal((await call('POST','/api/checkout',{items:['vortex-bedwars']})).status,401);
  const profile=await call('PATCH','/api/me/profile',{name:'Jogador',minecraft_nick:'NovoNick'},customer);assert.equal(profile.data.minecraft_nick,'NovoNick');
  assert.equal((await call('PATCH','/api/me/profile',{name:'Jogador',minecraft_nick:'../../wrong'},customer)).status,400);
  const catalog=(await call('GET','/api/products')).data;assert.equal(catalog.length,5);assert.equal(catalog.find(p=>p.slug==='vortex-bedwars').price_cents,15000);assert.ok(catalog.every(p=>p.minecraft_versions==='1.21'));
  assert.equal((await call('POST','/api/admin/coupons',{code:'VORTEX10',discount_type:'percent',discount_value:10,max_uses:1},admin)).status,201);
  const cart={items:['vortex-bedwars','vortex-feast'],coupon:'VORTEX10',request_id:crypto.randomUUID(),amount_cents:1};
  assert.equal((await call('POST','/api/cart/quote',cart,customer)).data.amount_cents,15300);
  const purchase=await call('POST','/api/checkout',cart,customer);assert.equal(purchase.status,201,JSON.stringify(purchase));
  const again=await call('POST','/api/checkout',cart,customer);assert.equal(again.data.checkout_id,purchase.data.checkout_id);assert.equal(preferenceCount,1);
  assert.equal((await call('POST','/api/checkout',{...cart,request_id:crypto.randomUUID()},admin)).status,400);
  payments['100']={id:'100',status:'approved',currency_id:'BRL',transaction_amount:153,external_reference:'cart:'+purchase.data.checkout_id};
  assert.equal((await call('POST','/api/me/reconcile',{payment_id:'100'},admin)).status,409);
  assert.equal((await call('POST','/api/me/reconcile',{payment_id:'100'},customer)).status,200);
  assert.equal((await call('POST','/api/mercadopago/webhook',{data:{id:'100'}})).status,200);
  const licenses=(await call('GET','/api/me/licenses',undefined,customer)).data;assert.equal(licenses.length,2);assert.ok(licenses.every(l=>l.key&&l.status==='active'));assert.ok(licenses.some(l=>l.slug==='vortex-bedwars'));
  const bed=licenses.find(l=>l.slug==='vortex-bedwars');
  assert.equal((await call('POST','/api/licenses/'+bed.id+'/ip',{ip:'127.0.0.1'},customer)).status,200);
  assert.equal((await call('POST','/api/licenses/'+bed.id+'/ip',{ip:'203.0.113.10'},customer)).status,409);
  assert.equal((await call('DELETE','/api/licenses/'+bed.id+'/ip',{ip:'127.0.0.1'},admin)).status,404);
  assert.equal((await call('POST','/api/license/verify',{key:bed.key,product:'vortex-bedwars',ip:'203.0.113.10'})).data.ip_authorized,true);
  const grant=await call('POST','/api/admin/licenses',{user_id:b.data.user.id,product:'vortex-bedwars'},admin);assert.equal(grant.status,201,JSON.stringify(grant));
  assert.equal((await call('DELETE','/api/admin/licenses/'+grant.data.license_id,undefined,admin)).status,200);
  const ticket=await call('POST','/api/support/tickets',{subject:'Configuração do BedWars',message:'Preciso de ajuda.'},customer);assert.equal(ticket.status,201);
  const message=await call('POST','/api/support/tickets/'+ticket.data.id+'/messages',{body:'Vamos ajudar com a configuração.'},admin);assert.equal(message.status,201);
  assert.equal((await call('GET','/api/support/tickets/'+ticket.data.id,undefined,customer)).data.messages.length,2);
  assert.equal((await call('POST','/api/support/tickets/'+ticket.data.id+'/close',{},admin)).status,200);
  assert.equal((await call('POST','/api/support/tickets/'+ticket.data.id+'/messages',{body:'test'},customer)).status,409);
  payments['100'].status='refunded';payments['100'].transaction_amount_refunded=153;
  await call('POST','/api/mercadopago/webhook',{data:{id:'100'}});
  assert.ok((await call('GET','/api/me/licenses',undefined,customer)).data.every(l=>l.status==='suspended'));
  assert.equal((await call('POST','/api/license/verify',{key:bed.key,product:'vortex-bedwars'})).status,403);
  // Redo the additive migration without losing the customer's account or the orders.
  await db.exec(migration);assert.equal((await call('GET','/api/me',undefined,customer)).data.minecraft_nick,'NovoNick');
  assert.equal((await db.query("SELECT used_count FROM coupons WHERE code='VORTEX10'")).rows[0].used_count,1);
});
