const API='https://vortexcollections-api.onrender.com',token=localStorage.getItem('vortex_token');
const $=s=>document.querySelector(s);
const req=async(p,o={})=>{if(!token){location.href='index.html#cliente';throw Error('Faça login para abrir um chamado.')}const r=await fetch(API+p,{...o,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,...o.headers}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Falha no suporte.');return d};
const msg=t=>$('.portal-message').textContent=t;
const style=document.createElement('style');style.textContent='.support-conversation{margin-top:22px}.support-conversation-head{display:flex;justify-content:space-between;align-items:flex-start;gap:18px}.support-thread{min-height:230px;max-height:420px;overflow:auto;padding:16px;border:1px solid #75cbff2b;border-radius:12px;background:linear-gradient(180deg,#091320,#0d1d2d);margin-top:14px}.support-empty{color:#9db2c8!important;text-align:center;padding:36px 12px}.ticket-select{display:flex;flex-direction:column;align-items:flex-start;gap:5px;text-align:left;width:100%;padding:15px;border:1px solid #75cbff2b;border-radius:10px;background:#0b1726;color:#fff;cursor:pointer}.ticket-select:hover{border-color:#8ee5b9;background:#12243a}.ticket-select small,.ticket-status{color:#9db2c8}.chat-message{max-width:84%;margin:10px 0;padding:12px 14px;border-radius:14px;background:#172d45;border:1px solid #75cbff2b}.chat-message.from-customer{margin-right:auto;border-bottom-left-radius:4px}.chat-message.from-staff{margin-left:auto;background:linear-gradient(135deg,#14543f,#1b7255);border-color:#8ee5b955;border-bottom-right-radius:4px}.chat-message strong{display:block;font-size:12px;color:#c9e9ff}.chat-message p{margin:5px 0;color:#fff;white-space:pre-wrap}.chat-message small{display:block;color:#b8cadb;font-size:10px}.support-reply{display:flex;gap:10px;margin-top:14px}.support-reply textarea{flex:1;min-height:70px;resize:vertical;padding:12px;background:#091320;color:#fff;border:1px solid #56758e;border-radius:7px;font:inherit}.support-reply .btn{align-self:flex-end}@media(max-width:720px){.support-reply{flex-direction:column}.support-reply .btn{align-self:stretch}}';document.head.append(style);
const make=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n};
let selected=null;const polish=document.createElement('link');polish.rel='stylesheet';polish.href='chat-polish.css';document.head.append(polish);
const thread=make('section',undefined,'portal-card support-conversation');thread.innerHTML='<div class="support-conversation-head"><div><span class="section-kicker">CONVERSA</span><h2 id="thread-title">Selecione um chamado</h2></div><span id="thread-status" class="ticket-status"></span></div><div id="thread-messages" class="support-thread"><p class="support-empty">Escolha um chamado ao lado para ver as mensagens.</p></div><form id="reply-form" class="support-reply" hidden><textarea name="body" required maxlength="5000" placeholder="Escreva sua resposta..."></textarea><button class="btn btn-primary">Enviar resposta</button></form>';
document.querySelector('main').append(thread);
function renderThread(d){selected=d.ticket.id;$('#thread-title').textContent=d.ticket.subject;$('#thread-status').textContent=d.ticket.status;const box=$('#thread-messages');box.replaceChildren();d.messages.forEach(m=>{const b=make('article',undefined,'chat-message '+(String(m.author_id)===String(d.ticket.user_id)?'from-customer':'from-staff'));b.append(make('strong',m.author_name),make('p',m.body),make('small',new Date(m.created_at).toLocaleString('pt-BR')));box.append(b)});$('#reply-form').hidden=false;box.scrollTop=box.scrollHeight}
async function openTicket(id){try{renderThread(await req('/api/support/tickets/'+id))}catch(e){msg(e.message)}}
async function load(){try{const list=await req('/api/support/tickets');$('#tickets').replaceChildren();if(!list.length)$('#tickets').append(make('p','Você ainda não abriu chamados.','support-empty'));list.forEach(t=>{const row=make('button',undefined,'ticket-select');row.type='button';row.append(make('strong',t.subject),make('small',t.status+' · '+new Date(t.updated_at).toLocaleString('pt-BR')));row.onclick=()=>openTicket(t.id);$('#tickets').append(row)})}catch(e){msg(e.message)}}
$('#new-ticket').onsubmit=async e=>{e.preventDefault();try{const f=e.currentTarget;const created=await req('/api/support/tickets',{method:'POST',body:JSON.stringify({subject:f.subject.value,message:f.message.value})});f.reset();msg('Chamado enviado.');await load();await openTicket(created.id)}catch(x){msg(x.message)}};
$('#reply-form').onsubmit=async e=>{e.preventDefault();if(!selected)return;const b=e.currentTarget.querySelector('button');b.disabled=true;try{await req('/api/support/tickets/'+selected+'/messages',{method:'POST',body:JSON.stringify({body:e.currentTarget.body.value.trim()})});e.currentTarget.reset();await openTicket(selected);await load()}catch(x){msg(x.message)}finally{b.disabled=false}};
load();
